import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
    title: 'Fake Location',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div className="flex flex-col flex-grow relative">
                    <Toaster/>
                    <Image
                        src={'/background.jpg'}
                        alt="backgroundImage"
                        width={1440}
                        height={1024}
                        className="w-screen h-screen bg-gradient-to-br from-pink-200 via-transparent to-transparent bg-lightgray bg-center bg-cover "
                    />
                    <div className='absolute'>{children}</div>
                </div>
            </body>
        </html>
    );
}
